# Generated by Django 4.1.1 on 2022-10-03 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msngr', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Room',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(help_text='Room name', max_length=64, unique=True)),
        #         ('online', models.ManyToManyField(related_name='rooms', to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),

    ]
